const express = require('express')
const mongoose  = require('mongoose')
const cors = require('cors')
const user = require('./Api/UsersApi')
const doc = require('./Api/CoursApi')
const ann = require('./Api/AnnoncesApi')
const app = express()

app.use(cors())
app.use(express.json())
app.listen(4000,()=> console.log('serveur en cours d\'execution ...'))
mongoose.connect('mongodb://127.0.0.1:27017/Projet')
var conn = mongoose.connection
conn.on('connected',()=> console.log('serveur en cours d\'éxécution'))
conn.on('disconnected',()=> console.log('serveur déconnecté'))
conn.on('error',()=> console.error.bind('erreur de connexion'))
app.use('/User', user)
app.use('/Cours', doc)
app.use('/Annonce', ann)
app.use('/Images', express.static('Images'))
app.use('/Videos', express.static('Videos'))
app.use('/Docs', express.static('Docs'))
module.exports = conn